// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4N_2y9TdNixA8SzBmHvlRTLmL-i0m_0',
    appId: '1:594576568399:web:96fbd64556f307f4f8ba3a',
    messagingSenderId: '594576568399',
    projectId: 'ecolens-e868f',
    authDomain: 'ecolens-e868f.firebaseapp.com',
    storageBucket: 'ecolens-e868f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXfT1Xl6FyA6QWus9MtrcJ8LW2Ua3Bi4',
    appId: '1:594576568399:android:3ddf7015d59d71acf8ba3a',
    messagingSenderId: '594576568399',
    projectId: 'ecolens-e868f',
    storageBucket: 'ecolens-e868f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzekAIcGppGm-ffDgCQIx0PwibXJEQqlM',
    appId: '1:594576568399:ios:c4dab58d9b8e7b27f8ba3a',
    messagingSenderId: '594576568399',
    projectId: 'ecolens-e868f',
    storageBucket: 'ecolens-e868f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzekAIcGppGm-ffDgCQIx0PwibXJEQqlM',
    appId: '1:594576568399:ios:c4dab58d9b8e7b27f8ba3a',
    messagingSenderId: '594576568399',
    projectId: 'ecolens-e868f',
    storageBucket: 'ecolens-e868f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4N_2y9TdNixA8SzBmHvlRTLmL-i0m_0',
    appId: '1:594576568399:web:ba970e11c1ec196bf8ba3a',
    messagingSenderId: '594576568399',
    projectId: 'ecolens-e868f',
    authDomain: 'ecolens-e868f.firebaseapp.com',
    storageBucket: 'ecolens-e868f.firebasestorage.app',
  );
}
